"""add social_id to User

Revision ID: 2ed1c1a9659b
Revises: None
Create Date: 2016-05-08 00:39:26.255675

"""

# revision identifiers, used by Alembic.
revision = '2ed1c1a9659b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_id', sa.String(length=64)))


def downgrade():
    pass
